# Generated by Django 4.2.1 on 2023-07-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABADUAPP', '0002_blog_alter_gallery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogpost',
        ),
    ]
