# Generated by Django 4.2.1 on 2023-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABADUAPP', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
